use_frameworks!

platform :ios, '8.0'

target 'FSLocalizations_Example' do
  pod 'FSLocalizations', :path => '../'

  target 'FSLocalizations_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
